import React, { useState } from 'react';
import './AssetReport.css';

const AssetReport = ({ results, onReset, onComplete }) => {
  const [expandedAssets, setExpandedAssets] = useState({});

  const toggleAsset = (index) => {
    setExpandedAssets(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  const getAssetIcon = (type) => {
    const icons = {
      'Bank Account': '🏦',
      'Investment': '📈',
      'Retirement': '👴',
      'Real Estate': '🏠',
      'Business': '💼',
      'Life Insurance': '🛡️',
      'Other': '📋'
    };
    return icons[type] || '📋';
  };

  const getPriorityClass = (type) => {
    const highPriority = ['Life Insurance', 'Retirement', 'Real Estate'];
    return highPriority.includes(type) ? 'high-priority' : '';
  };

  const downloadReport = () => {
    const reportText = generateTextReport(results);
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Asset-Discovery-Report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateTextReport = (results) => {
    let report = `ASSET DISCOVERY REPORT
Generated: ${new Date().toLocaleDateString()}
======================================

SUMMARY
-------
Total Unique Assets Found: ${results.totalUniqueAssets}
Tax Returns Analyzed: ${results.analyzedReturns?.length || 0}

POTENTIAL ASSETS IDENTIFIED
---------------------------
`;

    results.consolidatedAssets.forEach((asset, index) => {
      report += `
${index + 1}. ${asset.type.toUpperCase()}
   Institution: ${asset.institution}
   Description: ${asset.description}
   Evidence: ${asset.evidence}
   Years Found: ${asset.yearsFound?.join(', ') || 'N/A'}
   Estimated Value: ${asset.estimatedValue || 'To be determined'}
   Action Required: ${asset.actionRequired}
`;
    });

    report += `
RECOMMENDATIONS
---------------
`;
    results.recommendations.forEach((rec, index) => {
      report += `${index + 1}. ${rec}\n`;
    });

    report += `
======================================
This report was generated by AI analysis of tax returns.
All potential assets should be verified with the respective institutions.
`;

    return report;
  };

  return (
    <div className="asset-report">
      <div className="report-header">
        <div className="report-title">
          <h2>Asset Discovery Report</h2>
          <p className="report-date">Generated {new Date(results.analysisDate).toLocaleDateString()}</p>
        </div>
        <div className="report-summary-badge">
          <span className="count">{results.totalUniqueAssets}</span>
          <span className="label">Potential Assets Found</span>
        </div>
      </div>

      {results.totalUniqueAssets === 0 ? (
        <div className="no-assets">
          <p>No potential assets were identified from the uploaded tax returns.</p>
          <p>This could mean:</p>
          <ul>
            <li>The decedent had minimal financial accounts</li>
            <li>Assets may be held in trusts or other entities</li>
            <li>Additional documents may be needed for analysis</li>
          </ul>
        </div>
      ) : (
        <>
          <div className="assets-grid">
            {results.consolidatedAssets.map((asset, index) => (
              <div
                key={index}
                className={`asset-card ${getPriorityClass(asset.type)} ${expandedAssets[index] ? 'expanded' : ''}`}
              >
                <div className="asset-header" onClick={() => toggleAsset(index)}>
                  <span className="asset-icon">{getAssetIcon(asset.type)}</span>
                  <div className="asset-main-info">
                    <span className="asset-type">{asset.type}</span>
                    <span className="asset-institution">{asset.institution}</span>
                  </div>
                  <span className="expand-icon">{expandedAssets[index] ? '▼' : '▶'}</span>
                </div>

                {expandedAssets[index] && (
                  <div className="asset-details">
                    <div className="detail-row">
                      <label>Description:</label>
                      <span>{asset.description}</span>
                    </div>
                    <div className="detail-row">
                      <label>Evidence Found:</label>
                      <span className="evidence">{asset.evidence}</span>
                    </div>
                    <div className="detail-row">
                      <label>Years Found:</label>
                      <span>{asset.yearsFound?.join(', ') || 'N/A'}</span>
                    </div>
                    {asset.estimatedValue && (
                      <div className="detail-row">
                        <label>Estimated Value:</label>
                        <span className="value">{asset.estimatedValue}</span>
                      </div>
                    )}
                    <div className="detail-row action">
                      <label>Action Required:</label>
                      <span>{asset.actionRequired}</span>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>

          <div className="recommendations-section">
            <h3>Recommended Next Steps</h3>
            <ol>
              {results.recommendations.map((rec, index) => (
                <li key={index}>{rec}</li>
              ))}
            </ol>
          </div>
        </>
      )}

      <div className="report-actions">
        <button onClick={downloadReport} className="download-btn">
          Download Report
        </button>
        <button onClick={onReset} className="reset-btn">
          Analyze More Returns
        </button>
        {onComplete && (
          <button onClick={onComplete} className="complete-btn">
            Continue to Next Step
          </button>
        )}
      </div>

      <div className="report-disclaimer">
        <p><strong>Disclaimer:</strong> This report was generated by AI analysis of tax returns. All potential assets should be verified directly with the respective financial institutions. Some assets may not appear on tax returns (e.g., non-interest bearing accounts, certain life insurance policies).</p>
      </div>
    </div>
  );
};

export default AssetReport;
